### ISSUE TITLE
Withdrawn papers

### ISSUE THREAD

**Issue by Marcus9512** [Marcus9512/dd2430#8]
Some of the papers are withdrawn and contains 0 information. We might not want these files in our dataset

id                       BJgm2DkJgN
authors                        Test
title                     Withdrawn
abstract            Withdrawn Paper
accepted                      False
image_path    images/BJgm2DkJgN.png
Name: 0, dtype: object

**Comment by JonasRSV** [comment]
I think these are now filtered out by the code that removes papers with no valid front-page.
